### ISSUE TITLE
How to run is unclear in docs

### ISSUE THREAD

**Issue by LeaVerou** [jmhobbs/wp-to-11ty#1]
Hey, thanks for writing this! 

Exploring using it to migrate to 11ty, after the more popular https://github.com/benbalter/wordpress-to-jekyll-exporter failed to work on my blog.

Coming to this with zero experience of how Go works, I was quite puzzled reading the docs, and I figured it may help if I document my journey:

Given this is something I would only use once, I don't want to just add it in my `$PATH`, I just wanted to run it by referencing the file to execute. However, running something like `./wp-to-11ty -download-media ./leaverou.WordPress.2023-04-29.xml` produced a `./wp-to-11ty: command not found` response. 

Then I thought maybe the problem is I didn't have Go installed, so I went down a rabbit hole of installing that. After installing Go, I was still getting "command not found". I tried referencing `main.go` to execute, but still the same.

Then I tried `go run`, but that also produced errors:

```
leaverou@Leas-MBP Documents % sudo go run ./wp-to-11ty/main.go -download-media ./leaverou.WordPress.2023-04-29.xml
wp-to-11ty/main.go:17:2: no required module provides package github.com/fatih/color: go.mod file not found in current directory or any parent directory; see 'go help modules'
wp-to-11ty/main.go:18:2: no required module provides package gopkg.in/yaml.v2: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

Then I figured f*ck it, I'll just add it to my path and use `wp-to-11ty` as the command. Nope, still "command not found".

Then it dawned on me: maybe Go works like npm, and I basically need to find the equivalent `npm install -g`. This led me here https://stackoverflow.com/questions/36650052/golang-equivalent-of-npm-install-g

That didn't go so well either.

```
leaverou@Leas-MBP Documents % go install wp-to-11ty
go: 'go install' requires a version when current directory is not in a module
	Try 'go install wp-to-11ty@latest' to install the latest version
leaverou@Leas-MBP Documents % go install wp-to-11ty@latest
go: wp-to-11ty@latest: malformed module path "wp-to-11ty": missing dot in first path element
leaverou@Leas-MBP Documents % go install github.com/jmhobbs/wp-to-11ty@latest
go: downloading github.com/jmhobbs/wp-to-11ty v0.0.1
go: github.com/jmhobbs/wp-to-11ty@latest: module github.com/jmhobbs/wp-to-11ty@latest found (v0.0.1), but does not contain package github.com/jmhobbs/wp-to-11ty
```

At that point I gave up and started googling other solutions. I ended up on https://github.com/lonekorean/wordpress-export-to-markdown which seemed to work better, though I ended up on different rabbit holes. But that's a story for another day 😅

Other things:

- The docs list what is the default for `-output` but not for `-download-media`. Looking at the code it seems to be `false` but it may be good to mention. Also, why would the default not be `true`? It's hard to imagine many use cases where one *doesn't* want to download media.

Hope this helps!

**Comment by jmhobbs** [comment]
Hi @LeaVerou!

Thank you for your detailed issue, and I'm super sorry you lost time on this.  I had never really expected other folks to use this, I just thought since I wrote all the code I should put it out there.  I will _totally_ fixup these docs though so no one else gets bit in the same way.

I _believe_ I went with `false` because I didn't write in anything to keep it from downloading the same media more than once and I didn't want to wait around for it on my slow internet at the time.

Also, `wordpress-export-to-markdown` looks really great, wish I had found that before I wrote all this code 😂

**Comment by jmhobbs** [comment]
Docs are tuned up and binaries are being auto-built with an action!  Thanks again!

**Comment by LeaVerou** [comment]
> Hi @LeaVerou!
> 
> Thank you for your detailed issue, and I'm super sorry you lost time on this. I had never really expected other folks to use this, I just thought since I wrote all the code I should put it out there. I will _totally_ fixup these docs though so no one else gets bit in the same way.

Please don't be sorry! Every time someone releases code they wrote for themselves it's a win for the community, and I am immensely grateful, even though I did not end up using this. I only documented this in case it helps, it was not at all my intention to complain. 🙏🏼

But glad it helped make the docs more comprehensive! Btw I see `go install` is recommended, fwiw I did try that too, and also got errors (documented above). Not sure if it was something with my system, or I was doing something wrong. 🤷🏽‍♀️

**Comment by jmhobbs** [comment]
> But glad it helped make the docs more comprehensive! Btw I see go install is recommended, fwiw I did try that too, and also got errors (documented above). Not sure if it was something with my system, or I was doing something wrong. 

I'm not actually sure why that failed, do you know what Go version you were using?  That can be emitted by `go version`, as `go --version` is not a thing for some reason.   I tested what's in the README on my machine, but I have Go 1.20 installed, so it might be version related.

**Comment by LeaVerou** [comment]
I also have 1.20:

```
go version go1.20.3 darwin/amd64
```

**Comment by jmhobbs** [comment]
Well, I'm at a loss on that one.

I moved the binary download section above the Go install section, so hopefully most folks will choose that route.

Thanks again!
